"""Signal scorer — checks tonight's signals against actual game outcomes.

Run this AFTER games finish to score the signals generated by signal_generator.py.

It:
1. Loads signals from data/signals.json (generated pre-game)
2. Fetches settled market results from Kalshi (did player clear the line?)
3. Computes actual P&L with 7% Kalshi fee structure
4. Compares model accuracy vs market accuracy
5. Saves detailed results to data/signal_results/

Usage:
    python3 -m analysis.score_signals
    python3 -m analysis.score_signals --signals data/signals.json
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path

import requests

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

KALSHI_BASE = "https://api.elections.kalshi.com/trade-api/v2"
FEE_RATE = 0.07


def _get_market_result(ticker: str) -> dict | None:
    """Fetch current market status and result from Kalshi."""
    try:
        resp = requests.get(f"{KALSHI_BASE}/markets/{ticker}", timeout=10)
        if resp.status_code == 200:
            market = resp.json().get("market", resp.json())
            return {
                "status": market.get("status", ""),
                "result": market.get("result", ""),
                "last_price": market.get("last_price"),
                "volume": market.get("volume", 0),
            }
    except Exception:
        pass

    # Try historical endpoint
    try:
        resp = requests.get(f"{KALSHI_BASE}/historical/markets/{ticker}", timeout=10)
        if resp.status_code == 200:
            market = resp.json().get("market", resp.json())
            return {
                "status": market.get("status", ""),
                "result": market.get("result", ""),
                "last_price": market.get("last_price"),
                "volume": market.get("volume", 0),
            }
    except Exception:
        pass

    return None


def score_signals(signals_path: Path | None = None) -> dict:
    """Score pre-game signals against actual outcomes."""
    if signals_path is None:
        signals_path = _PROJECT_ROOT / "data" / "signals.json"

    if not signals_path.exists():
        print(f"No signals file at {signals_path}")
        print("Run signal_generator.py first to generate pre-game signals.")
        return {"error": "no_signals"}

    data = json.loads(signals_path.read_text())
    signals = data.get("signals", [])
    print(f"Loaded {len(signals)} signals from {signals_path.name}")

    # Score each signal
    results = []
    settled = 0
    still_open = 0
    errors = 0

    for i, sig in enumerate(signals):
        ticker = sig["ticker"]
        market = _get_market_result(ticker)

        if not market:
            errors += 1
            continue

        status = market["status"]
        result = market.get("result", "")

        if status not in ("finalized", "settled", "determined"):
            still_open += 1
            continue

        settled += 1

        # Determine outcome
        if sig["side"] == "YES":
            won = result == "yes"
            cost = sig["market_price"]  # what we'd pay (yes_ask)
            if won:
                gross_profit = 1.0 - cost
                net_profit = gross_profit * (1 - FEE_RATE)
            else:
                net_profit = -cost
        else:  # NO
            won = result == "no"
            cost = sig["cost_per_contract"]
            if won:
                gross_profit = 1.0 - cost
                net_profit = gross_profit * (1 - FEE_RATE)
            else:
                net_profit = -cost

        # Was the model's direction correct?
        if sig["side"] == "YES":
            model_correct = (sig["model_prob"] > 0.5 and result == "yes") or \
                           (sig["model_prob"] < 0.5 and result == "no")
        else:
            model_correct = (sig["model_prob"] > 0.5 and result == "no") or \
                           (sig["model_prob"] < 0.5 and result == "yes")

        results.append({
            **sig,
            "result": result,
            "won": won,
            "net_profit": round(net_profit, 4),
            "cost": round(cost, 4),
            "model_correct": model_correct,
        })

        if (i + 1) % 50 == 0:
            print(f"  Checked {i+1}/{len(signals)}: {settled} settled, {still_open} open")

        time.sleep(0.05)  # rate limiting

    if not results:
        print(f"\nNo settled markets yet ({still_open} still open, {errors} errors)")
        print("Run again after games finish.")
        return {"settled": 0, "still_open": still_open}

    # Compute aggregate metrics
    total_pnl = sum(r["net_profit"] for r in results)
    total_risked = sum(r["cost"] for r in results)
    wins = sum(1 for r in results if r["won"])
    model_correct_count = sum(1 for r in results if r["model_correct"])

    win_rate = wins / len(results) if results else 0
    model_accuracy = model_correct_count / len(results) if results else 0
    roi = (total_pnl / total_risked * 100) if total_risked > 0 else 0

    # Per-stat breakdown
    per_stat = {}
    for stat in set(r["stat"] for r in results):
        stat_results = [r for r in results if r["stat"] == stat]
        stat_wins = sum(1 for r in stat_results if r["won"])
        stat_pnl = sum(r["net_profit"] for r in stat_results)
        stat_risked = sum(r["cost"] for r in stat_results)
        per_stat[stat] = {
            "trades": len(stat_results),
            "wins": stat_wins,
            "win_rate": round(stat_wins / len(stat_results), 3) if stat_results else 0,
            "pnl": round(stat_pnl, 2),
            "roi": round(stat_pnl / stat_risked * 100, 1) if stat_risked > 0 else 0,
        }

    # By edge bucket
    edge_buckets = {"5-10%": [], "10-20%": [], "20-30%": [], "30%+": []}
    for r in results:
        e = r["edge"]
        if e >= 0.30:
            edge_buckets["30%+"].append(r)
        elif e >= 0.20:
            edge_buckets["20-30%"].append(r)
        elif e >= 0.10:
            edge_buckets["10-20%"].append(r)
        else:
            edge_buckets["5-10%"].append(r)

    # Save detailed results
    results_dir = _PROJECT_ROOT / "data" / "signal_results"
    results_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output = {
        "scored_at": datetime.now().isoformat(timespec="seconds"),
        "signals_file": str(signals_path),
        "total_signals": len(signals),
        "settled": len(results),
        "still_open": still_open,
        "summary": {
            "trades": len(results),
            "wins": wins,
            "win_rate": round(win_rate, 3),
            "model_accuracy": round(model_accuracy, 3),
            "total_pnl": round(total_pnl, 2),
            "total_risked": round(total_risked, 2),
            "roi": round(roi, 1),
        },
        "per_stat": per_stat,
        "results": results,
    }
    output_path = results_dir / f"results_{timestamp}.json"
    with open(output_path, "w") as f:
        json.dump(output, f, indent=2)

    # Print report
    print(f"\n{'='*70}")
    print(f"  SIGNAL SCORECARD")
    print(f"{'='*70}")
    print(f"  Signals scored:    {len(results)} of {len(signals)} ({still_open} still open)")
    print(f"  Win rate:          {win_rate:.1%} ({wins}/{len(results)})")
    print(f"  Model accuracy:    {model_accuracy:.1%}")
    print(f"  Total P&L:         ${total_pnl:+.2f} per contract")
    print(f"  Total risked:      ${total_risked:.2f}")
    print(f"  ROI:               {roi:+.1f}%")

    print(f"\n  By stat type:")
    for stat, data in sorted(per_stat.items(), key=lambda x: -x[1]["trades"]):
        print(f"    {stat:>15}: {data['trades']} trades, {data['win_rate']:.0%} win, "
              f"${data['pnl']:+.2f} P&L, {data['roi']:+.1f}% ROI")

    print(f"\n  By edge size:")
    for bucket, bucket_results in edge_buckets.items():
        if bucket_results:
            bw = sum(1 for r in bucket_results if r["won"])
            bp = sum(r["net_profit"] for r in bucket_results)
            br = sum(r["cost"] for r in bucket_results)
            print(f"    {bucket:>8}: {len(bucket_results)} trades, "
                  f"{bw/len(bucket_results):.0%} win, "
                  f"{bp/br*100:+.1f}% ROI" if br > 0 else "")

    # Show biggest winners and losers
    sorted_by_pnl = sorted(results, key=lambda r: r["net_profit"], reverse=True)
    print(f"\n  Top 5 winners:")
    for r in sorted_by_pnl[:5]:
        print(f"    {r['player']:<20} {r['stat']:>8} {r['line']:>3}+ {r['side']:>3} "
              f"edge={r['edge']:+.0%} → {'W' if r['won'] else 'L'} ${r['net_profit']:+.2f}")

    print(f"\n  Top 5 losers:")
    for r in sorted_by_pnl[-5:]:
        print(f"    {r['player']:<20} {r['stat']:>8} {r['line']:>3}+ {r['side']:>3} "
              f"edge={r['edge']:+.0%} → {'W' if r['won'] else 'L'} ${r['net_profit']:+.2f}")

    print(f"\n  Saved to: {output_path}")
    print(f"{'='*70}")

    return output


def main():
    parser = argparse.ArgumentParser(description="Score pre-game signals against outcomes")
    parser.add_argument("--signals", type=str, default=None)
    args = parser.parse_args()

    path = Path(args.signals) if args.signals else None
    score_signals(path)


if __name__ == "__main__":
    main()
